import { bookType } from '../../../types/book';

import {
  book01,
  book02,
  book03,
  book04,
  book05,
  book06,
  book07,
  book08,
  book09,
  book10,
  bookbg01,
  bookbg02,
  bookbg03,
  bookbg04,
  bookbg05,
  bookbg06,
  bookbg07,
  bookbg08,
  bookbg09,
  bookbg10,
} from '../../../assets/slide/bookImg';

export const bookData: bookType = [
  {
    id: 0,
    TITLE: '이토록 평범한 미래',
    AUTHOR: '김연수',
    KDC: '단편소설',
    SUBJECT: '국내',
    BOOKBG: `${bookbg01}`,
    BOOGIMG: `${book01}`,
    TITLE_URL: `9788954680004`,
    category1: '국내도서',
    category2: '소설/시/희곡',
    category3: '한국소설',
  },
  {
    id: 1,
    TITLE: '꿀딴지곰의 레트로 게임 대백과 - 열혈 겜돌이의 명작 고전 게임 추억 찾기 연구소',
    AUTHOR: '꿀딴지곰',
    KDC: '건강/취미',
    SUBJECT: '국내',
    BOOKBG: `${bookbg02}`,
    BOOGIMG: `${book02}`,
    TITLE_URL: `9788964945834`,
    category1: '국내도서',
    category2: '건강/취미',
    category3: '취미기타',
  },
  {
    id: 2,
    TITLE: '물고기는 존재하지 않는다 (리커버 특별판, 양장) - 상실, 사랑 그리고 숨어 있는 삶의 질서에 관한 이야기',
    AUTHOR: '룰루 밀러',
    KDC: '과학',
    SUBJECT: '국내',
    BOOKBG: `${bookbg03}`,
    BOOGIMG: `${book03}`,
    TITLE_URL: `9791189327156`,
    category1: '국내도서',
    category2: '과학',
    category3: '기초과학/교양과학',
  },
  {
    id: 3,
    TITLE: '불편한 편의점 2 (단풍 에디션)',
    AUTHOR: '김호연',
    KDC: '한국소설',
    SUBJECT: '국내',
    BOOKBG: `${bookbg04}`,
    BOOGIMG: `${book04}`,
    TITLE_URL: `9791161571379`,
    category1: '국내도서',
    category2: '소설/시/희곡',
    category3: '한국소설',
  },
  {
    id: 4,
    TITLE: '셜록 홈스 이스케이프 룸 퍼즐 ',
    AUTHOR: '제임스 해머모턴',
    KDC: '건강/취미',
    SUBJECT: '국내',
    BOOKBG: `${bookbg05}`,
    BOOGIMG: `${book05}`,
    TITLE_URL: `9788997943838`,
    category1: '국내도서',
    category2: '건강/취미',
    category3: '취미기타',
  },
  {
    id: 5,
    TITLE: '아버지의 해방일지',
    AUTHOR: '정지아',
    KDC: '한국소설',
    SUBJECT: '국내',
    BOOKBG: `${bookbg06}`,
    BOOGIMG: `${book06}`,
    TITLE_URL: `9788936438838`,
    category1: '국내도서',
    category2: '소설/시/희곡',
    category3: '한국소설',
  },
  {
    id: 6,
    TITLE: `인생의 역사 - '공무도하가'에서 '사랑의 발명'까지`,
    AUTHOR: '신형철',
    KDC: '한국에세이',
    SUBJECT: '국내',
    BOOKBG: `${bookbg07}`,
    BOOGIMG: `${book07}`,
    TITLE_URL: `9791191859379`,
    category1: '국내도서',
    category2: '에세이',
    category3: '명사에세이',
  },
  {
    id: 7,
    TITLE: '총살된 프랑스, 남겨진 편지',
    AUTHOR: '이용우',
    KDC: '프랑스사',
    SUBJECT: '국내',
    BOOKBG: `${bookbg08}`,
    BOOGIMG: `${book08}`,
    TITLE_URL: `9788976965776`,
    category1: '국내도서',
    category2: '역사',
    category3: '유럽사',
  },
  {
    id: 8,
    TITLE: 'TOKEVI 도깨비 2022.창간호',
    AUTHOR: 'TOKEVI 편집부',
    KDC: '잡지',
    SUBJECT: '국내',
    BOOKBG: `${bookbg09}`,
    BOOGIMG: `${book09}`,
    TITLE_URL: `9772800042009`,
    category1: '국내도서',
    category2: '잡지',
    category3: '교양/문예/인문',
  },
  {
    id: 9,
    TITLE: '2023 트렌드 노트 - 새로운 소비주체의 등장',
    AUTHOR: '이원희,박현영,최재연,정석환,신수정,신예은,심우연',
    KDC: '트렌드/미래전망',
    SUBJECT: '국내',
    BOOKBG: `${bookbg10}`,
    BOOGIMG: `${book10}`,
    TITLE_URL: `9791191211832`,
    category1: '국내도서',
    category2: '경제경영',
    category3: '트렌드/미래전망',
  },
];
