export const ALADINLIST = [
  {
    CID: 53495,
    category1: "국내도서",
    category2: "가정/요리/뷰티",
    category3: "나라별 요리",
  },
  {
    CID: 53497,
    category1: "국내도서",
    category2: "가정/요리/뷰티",
    category3: "술/음료/차",
  },
  {
    CID: 53500,
    category1: "국내도서",
    category2: "가정/요리/뷰티",
    category3: "뜨개질/바느질/DIY",
  },
  {
    CID: 53504,
    category1: "국내도서",
    category2: "가정/요리/뷰티",
    category3: "패션/뷰티",
  },
  {
    CID: 53510,
    category1: "국내도서",
    category2: "가정/요리/뷰티",
    category3: "결혼/가족",
  },
  {
    CID: 103031,
    category1: "외국도서",
    category2: "가정/원예/인테리어",
    category3: "가정",
  },
  {
    CID: 103032,
    category1: "외국도서",
    category2: "가정/원예/인테리어",
    category3: "가정",
  },
  {
    CID: 103048,
    category1: "외국도서",
    category2: "가정/원예/인테리어",
    category3: "원예",
  },
  {
    CID: 103049,
    category1: "외국도서",
    category2: "가정/원예/인테리어",
    category3: "원예",
  },
  {
    CID: 103050,
    category1: "외국도서",
    category2: "가정/원예/인테리어",
    category3: "원예",
  },
  {
    CID: 105132,
    category1: "외국도서",
    category2: "가정/원예/인테리어",
    category3: "원예",
  },
  {
    CID: 105133,
    category1: "외국도서",
    category2: "가정/원예/인테리어",
    category3: "원예",
  },
  {
    CID: 105134,
    category1: "외국도서",
    category2: "가정/원예/인테리어",
    category3: "원예",
  },
  {
    CID: 103091,
    category1: "외국도서",
    category2: "건강/스포츠",
    category3: "건강",
  },
  {
    CID: 103133,
    category1: "외국도서",
    category2: "건강/스포츠",
    category3: "반려동물",
  },
  {
    CID: 103144,
    category1: "외국도서",
    category2: "건강/스포츠",
    category3: "스포츠/레크레이션",
  },
  {
    CID: 53537,
    category1: "국내도서",
    category2: "건강/취미/레저",
    category3: "건강운동",
  },
  {
    CID: 53540,
    category1: "국내도서",
    category2: "건강/취미/레저",
    category3: "질병치료와 예방",
  },
  {
    CID: 53562,
    category1: "국내도서",
    category2: "건강/취미/레저",
    category3: "건강정보",
  },
  {
    CID: 53567,
    category1: "국내도서",
    category2: "건강/취미/레저",
    category3: "스포츠/레저 기타",
  },
  {
    CID: 53573,
    category1: "국내도서",
    category2: "건강/취미/레저",
    category3: "원예",
  },
  {
    CID: 53578,
    category1: "국내도서",
    category2: "건강/취미/레저",
    category3: "취미기타",
  },
  {
    CID: 54711,
    category1: "국내도서",
    category2: "건강/취미/레저",
    category3: "구기",
  },
  {
    CID: 268,
    category1: "국내도서",
    category2: "경제경영",
    category3: "마케팅/세일즈",
  },
  {
    CID: 852,
    category1: "국내도서",
    category2: "경제경영",
    category3: "기업/경영자 스토리",
  },
  {
    CID: 2173,
    category1: "국내도서",
    category2: "경제경영",
    category3: "기업 경영",
  },
  {
    CID: 3059,
    category1: "국내도서",
    category2: "경제경영",
    category3: "경제학/경제일반",
  },
  {
    CID: 3103,
    category1: "국내도서",
    category2: "경제경영",
    category3: "기업 경영",
  },
  {
    CID: 141092,
    category1: "국내도서",
    category2: "경제경영",
    category3: "재테크/투자",
  },
  {
    CID: 103260,
    category1: "외국도서",
    category2: "경제경영",
    category3: "경제발전",
  },
  {
    CID: 103264,
    category1: "외국도서",
    category2: "경제경영",
    category3: "경제학/경제일반 ",
  },
  {
    CID: 103269,
    category1: "외국도서",
    category2: "경제경영",
    category3: "경제학/경제일반 ",
  },
  {
    CID: 103272,
    category1: "외국도서",
    category2: "경제경영",
    category3: "국제경제",
  },
  {
    CID: 103286,
    category1: "외국도서",
    category2: "경제경영",
    category3: "보험",
  },
  {
    CID: 103298,
    category1: "외국도서",
    category2: "경제경영",
    category3: "비영리 기구",
  },
  {
    CID: 103320,
    category1: "외국도서",
    category2: "경제경영",
    category3: "재무/회계",
  },
  {
    CID: 103327,
    category1: "외국도서",
    category2: "경제경영",
    category3: "전자상거래 (E-Commerce)",
  },
  {
    CID: 222,
    category1: "국내도서",
    category2: "고전",
    category3: "서양고전문학",
  },
  {
    CID: 2138,
    category1: "국내도서",
    category2: "고전",
    category3: "서양고전문학",
  },
  {
    CID: 2149,
    category1: "국내도서",
    category2: "고전",
    category3: "서양고전문학",
  },
  {
    CID: 2314,
    category1: "국내도서",
    category2: "고전",
    category3: "서양고전문학",
  },
  {
    CID: 4378,
    category1: "국내도서",
    category2: "고전",
    category3: "동양고전문학",
  },
  {
    CID: 4437,
    category1: "국내도서",
    category2: "고전",
    category3: "동양고전사상",
  },
  {
    CID: 4438,
    category1: "국내도서",
    category2: "고전",
    category3: "동양고전사상",
  },
  {
    CID: 4440,
    category1: "국내도서",
    category2: "고전",
    category3: "우리나라 옛글",
  },
  {
    CID: 51160,
    category1: "국내도서",
    category2: "과학",
    category3: "과학의 이해",
  },
  {
    CID: 51283,
    category1: "국내도서",
    category2: "과학",
    category3: "동물과 식물",
  },
  {
    CID: 51285,
    category1: "국내도서",
    category2: "과학",
    category3: "동물과 식물",
  },
  {
    CID: 51293,
    category1: "국내도서",
    category2: "과학",
    category3: "물리학",
  },
  {
    CID: 51318,
    category1: "국내도서",
    category2: "과학",
    category3: "지구과학",
  },
  {
    CID: 51337,
    category1: "국내도서",
    category2: "과학",
    category3: "화학",
  },
  {
    CID: 51365,
    category1: "국내도서",
    category2: "과학",
    category3: "공학",
  },
  {
    CID: 120980,
    category1: "국내도서",
    category2: "과학",
    category3: "농업",
  },
  {
    CID: 2556,
    category1: "국내도서",
    category2: "만화",
    category3: "본격장르만화",
  },
  {
    CID: 2558,
    category1: "국내도서",
    category2: "만화",
    category3: "소년만화",
  },
  {
    CID: 4669,
    category1: "국내도서",
    category2: "만화",
    category3: "교양만화",
  },
  {
    CID: 6130,
    category1: "국내도서",
    category2: "만화",
    category3: "순정만화",
  },
  {
    CID: 13972,
    category1: "국내도서",
    category2: "만화",
    category3: "만화작가파일",
  },
  {
    CID: 33125,
    category1: "국내도서",
    category2: "만화",
    category3: "유럽/서구만화",
  },
  {
    CID: 53820,
    category1: "국내도서",
    category2: "만화",
    category3: "만화그리기와 읽기",
  },
  {
    CID: 103618,
    category1: "외국도서",
    category2: "만화",
    category3: "일본만화",
  },
  {
    CID: 103619,
    category1: "외국도서",
    category2: "만화",
    category3: "일본만화",
  },
  {
    CID: 51068,
    category1: "국내도서",
    category2: "사회과학",
    category3: "비평/칼럼",
  },
  {
    CID: 51086,
    category1: "국내도서",
    category2: "사회과학",
    category3: "사회문제",
  },
  {
    CID: 51111,
    category1: "국내도서",
    category2: "사회과학",
    category3: "교육학",
  },
  {
    CID: 51121,
    category1: "국내도서",
    category2: "사회과학",
    category3: "교육학",
  },
  {
    CID: 51231,
    category1: "국내도서",
    category2: "사회과학",
    category3: "정치학/외교학/행정학",
  },
  {
    CID: 51346,
    category1: "국내도서",
    category2: "사회과학",
    category3: "언론/미디어",
  },
  {
    CID: 51396,
    category1: "국내도서",
    category2: "사회과학",
    category3: "국방/군사학",
  },
  {
    CID: 51411,
    category1: "국내도서",
    category2: "사회과학",
    category3: "국방/군사학",
  },
  {
    CID: 51055,
    category1: "국내도서",
    category2: "소설/시/희곡",
    category3: "세계의 소설",
  },
  {
    CID: 51067,
    category1: "국내도서",
    category2: "소설/시/희곡",
    category3: "추리/미스터리소설",
  },
  {
    CID: 51116,
    category1: "국내도서",
    category2: "소설/시/희곡",
    category3: "라이트 노벨",
  },
  {
    CID: 51234,
    category1: "국내도서",
    category2: "소설/시/희곡",
    category3: "문학 잡지",
  },
  {
    CID: 51237,
    category1: "국내도서",
    category2: "소설/시/희곡",
    category3: "테마문학",
  },
  {
    CID: 51286,
    category1: "국내도서",
    category2: "소설/시/희곡",
    category3: "세계의 문학",
  },
  {
    CID: 69256,
    category1: "국내도서",
    category2: "소설/시/희곡",
    category3: "시",
  },
  {
    CID: 181723,
    category1: "국내도서",
    category2: "소설/시/희곡",
    category3: "로맨스소설",
  },
  {
    CID: 103639,
    category1: "외국도서",
    category2: "소설/시/희곡",
    category3: "문학",
  },
  {
    CID: 103664,
    category1: "외국도서",
    category2: "소설/시/희곡",
    category3: "문학비평",
  },
  {
    CID: 103696,
    category1: "외국도서",
    category2: "소설/시/희곡",
    category3: "소설",
  },
  {
    CID: 103699,
    category1: "외국도서",
    category2: "소설/시/희곡",
    category3: "소설",
  },
  {
    CID: 103752,
    category1: "외국도서",
    category2: "소설/시/희곡",
    category3: "시",
  },
  {
    CID: 103775,
    category1: "외국도서",
    category2: "소설/시/희곡",
    category3: "희곡",
  },
  {
    CID: 51423,
    category1: "국내도서",
    category2: "에세이",
    category3: "여행에세이",
  },
  {
    CID: 51431,
    category1: "국내도서",
    category2: "에세이",
    category3: "종교에세이",
  },
  {
    CID: 51843,
    category1: "국내도서",
    category2: "에세이",
    category3: "예술에세이",
  },
  {
    CID: 52906,
    category1: "국내도서",
    category2: "에세이",
    category3: "명사에세이",
  },
  {
    CID: 50847,
    category1: "국내도서",
    category2: "여행",
    category3: "국내 여행가이드",
  },
  {
    CID: 50858,
    category1: "국내도서",
    category2: "여행",
    category3: "동남아시아여행",
  },
  {
    CID: 50872,
    category1: "국내도서",
    category2: "여행",
    category3: "기타지역여행",
  },
  {
    CID: 50874,
    category1: "국내도서",
    category2: "여행",
    category3: "테마여행",
  },
  {
    CID: 50894,
    category1: "국내도서",
    category2: "여행",
    category3: "지도",
  },
  {
    CID: 63850,
    category1: "국내도서",
    category2: "여행",
    category3: "독일여행",
  },
  {
    CID: 64303,
    category1: "국내도서",
    category2: "여행",
    category3: "괌/사이판/하와이여행",
  },
  {
    CID: 110288,
    category1: "국내도서",
    category2: "여행",
    category3: "동유럽여행",
  },
  {
    CID: 103813,
    category1: "외국도서",
    category2: "여행",
    category3: "남아메리카",
  },
  {
    CID: 103819,
    category1: "외국도서",
    category2: "여행",
    category3: "미국",
  },
  {
    CID: 103825,
    category1: "외국도서",
    category2: "여행",
    category3: "아시아",
  },
  {
    CID: 103834,
    category1: "외국도서",
    category2: "여행",
    category3: "아프리카",
  },
  {
    CID: 103843,
    category1: "외국도서",
    category2: "여행",
    category3: "유럽",
  },
  {
    CID: 103859,
    category1: "외국도서",
    category2: "여행",
    category3: "중동",
  },
  {
    CID: 103863,
    category1: "외국도서",
    category2: "여행",
    category3: "캐나다",
  },
  {
    CID: 103870,
    category1: "외국도서",
    category2: "여행",
    category3: "테마별 여행",
  },
  {
    CID: 88,
    category1: "국내도서",
    category2: "역사",
    category3: "테마로 보는 역사",
  },
  {
    CID: 113,
    category1: "국내도서",
    category2: "역사",
    category3: "한국고대~고려시대",
  },
  {
    CID: 165,
    category1: "국내도서",
    category2: "역사",
    category3: "유럽사",
  },
  {
    CID: 3431,
    category1: "국내도서",
    category2: "역사",
    category3: "한국근현대사",
  },
  {
    CID: 52607,
    category1: "국내도서",
    category2: "역사",
    category3: "이슬람/중동/이스라엘",
  },
  {
    CID: 52611,
    category1: "국내도서",
    category2: "역사",
    category3: "전쟁/분쟁사",
  },
  {
    CID: 103882,
    category1: "외국도서",
    category2: "역사",
    category3: "고대",
  },
  {
    CID: 103886,
    category1: "외국도서",
    category2: "역사",
    category3: "군사",
  },
  {
    CID: 103913,
    category1: "외국도서",
    category2: "역사",
    category3: "라틴아메리카",
  },
  {
    CID: 103920,
    category1: "외국도서",
    category2: "역사",
    category3: "미국",
  },
  {
    CID: 103925,
    category1: "외국도서",
    category2: "역사",
    category3: "아시아",
  },
  {
    CID: 103932,
    category1: "외국도서",
    category2: "역사",
    category3: "아프리카",
  },
  {
    CID: 103938,
    category1: "외국도서",
    category2: "역사",
    category3: "유럽",
  },
  {
    CID: 103939,
    category1: "외국도서",
    category2: "역사",
    category3: "유럽",
  },
  {
    CID: 50963,
    category1: "국내도서",
    category2: "예술/대중문화",
    category3: "예술/대중문화의 이해",
  },
  {
    CID: 50987,
    category1: "국내도서",
    category2: "예술/대중문화",
    category3: "미술",
  },
  {
    CID: 50989,
    category1: "국내도서",
    category2: "예술/대중문화",
    category3: "미술",
  },
  {
    CID: 51020,
    category1: "국내도서",
    category2: "예술/대중문화",
    category3: "음악",
  },
  {
    CID: 51091,
    category1: "국내도서",
    category2: "예술/대중문화",
    category3: "디자인/공예",
  },
  {
    CID: 51092,
    category1: "국내도서",
    category2: "예술/대중문화",
    category3: "디자인/공예",
  },
  {
    CID: 51093,
    category1: "국내도서",
    category2: "예술/대중문화",
    category3: "무용",
  },
  {
    CID: 51178,
    category1: "국내도서",
    category2: "예술/대중문화",
    category3: "TV/라디오",
  },
  {
    CID: 103960,
    category1: "외국도서",
    category2: "예술/대중문화",
    category3: "댄스",
  },
  {
    CID: 103969,
    category1: "외국도서",
    category2: "예술/대중문화",
    category3: "미술",
  },
  {
    CID: 103994,
    category1: "외국도서",
    category2: "예술/대중문화",
    category3: "사진",
  },
  {
    CID: 104009,
    category1: "외국도서",
    category2: "예술/대중문화",
    category3: "연극",
  },
  {
    CID: 104017,
    category1: "외국도서",
    category2: "예술/대중문화",
    category3: "영화/비디오",
  },
  {
    CID: 104028,
    category1: "외국도서",
    category2: "예술/대중문화",
    category3: "예술",
  },
  {
    CID: 104040,
    category1: "외국도서",
    category2: "예술/대중문화",
    category3: "음악",
  },
  {
    CID: 104055,
    category1: "외국도서",
    category2: "예술/대중문화",
    category3: "TV/라디오",
  },
  {
    CID: 4158,
    category1: "국내도서",
    category2: "외국어",
    category3: "어학사전",
  },
  {
    CID: 49844,
    category1: "국내도서",
    category2: "외국어",
    category3: "영어사전",
  },
  {
    CID: 49853,
    category1: "국내도서",
    category2: "외국어",
    category3: "영어회화",
  },
  {
    CID: 49865,
    category1: "국내도서",
    category2: "외국어",
    category3: "텝스",
  },
  {
    CID: 49883,
    category1: "국내도서",
    category2: "외국어",
    category3: "영어시험대비",
  },
  {
    CID: 49888,
    category1: "국내도서",
    category2: "외국어",
    category3: "일본어",
  },
  {
    CID: 49913,
    category1: "국내도서",
    category2: "외국어",
    category3: "중국어",
  },
  {
    CID: 49938,
    category1: "국내도서",
    category2: "외국어",
    category3: "통역/번역",
  },
  {
    CID: 104066,
    category1: "외국도서",
    category2: "요리",
    category3: "건강요리/치료식",
  },
  {
    CID: 104078,
    category1: "외국도서",
    category2: "요리",
    category3: "국가별 요리",
  },
  {
    CID: 104080,
    category1: "외국도서",
    category2: "요리",
    category3: "국가별 요리",
  },
  {
    CID: 104081,
    category1: "외국도서",
    category2: "요리",
    category3: "국가별 요리",
  },
  {
    CID: 104113,
    category1: "외국도서",
    category2: "요리",
    category3: "술/음료/차",
  },
  {
    CID: 104120,
    category1: "외국도서",
    category2: "요리",
    category3: "요리방법",
  },
  {
    CID: 104136,
    category1: "외국도서",
    category2: "요리",
    category3: "요리재료",
  },
  {
    CID: 104148,
    category1: "외국도서",
    category2: "요리",
    category3: "코스/요리",
  },
  {
    CID: 104185,
    category1: "외국도서",
    category2: "유머",
    category3: "유머",
  },
  {
    CID: 104188,
    category1: "외국도서",
    category2: "의학",
    category3: "간호학",
  },
  {
    CID: 104211,
    category1: "외국도서",
    category2: "의학",
    category3: "외과",
  },
  {
    CID: 104220,
    category1: "외국도서",
    category2: "의학",
    category3: "의료 서비스",
  },
  {
    CID: 104230,
    category1: "외국도서",
    category2: "의학",
    category3: "정신의학",
  },
  {
    CID: 104233,
    category1: "외국도서",
    category2: "의학",
    category3: "치과학",
  },
  {
    CID: 104241,
    category1: "외국도서",
    category2: "인문/사회",
    category3: "사회과학",
  },
  {
    CID: 104294,
    category1: "외국도서",
    category2: "인문/사회",
    category3: "심리학",
  },
  {
    CID: 104326,
    category1: "외국도서",
    category2: "인문/사회",
    category3: "정치학",
  },
  {
    CID: 104359,
    category1: "외국도서",
    category2: "인문/사회",
    category3: "철학",
  },
  {
    CID: 51440,
    category1: "국내도서",
    category2: "인문학",
    category3: "철학 일반",
  },
  {
    CID: 51442,
    category1: "국내도서",
    category2: "인문학",
    category3: "서양철학",
  },
  {
    CID: 51444,
    category1: "국내도서",
    category2: "인문학",
    category3: "서양철학",
  },
  {
    CID: 51514,
    category1: "국내도서",
    category2: "인문학",
    category3: "심리학/정신분석학",
  },
  {
    CID: 51523,
    category1: "국내도서",
    category2: "인문학",
    category3: "신화/종교학",
  },
  {
    CID: 51538,
    category1: "국내도서",
    category2: "인문학",
    category3: "책읽기/글쓰기",
  },
  {
    CID: 51541,
    category1: "국내도서",
    category2: "인문학",
    category3: "기호학/언어학",
  },
  {
    CID: 51544,
    category1: "국내도서",
    category2: "인문학",
    category3: "인류학/고고학",
  },
  {
    CID: 2944,
    category1: "국내도서",
    category2: "자기계발",
    category3: "취업/진로/유망직업",
  },
  {
    CID: 3812,
    category1: "국내도서",
    category2: "자기계발",
    category3: "인간관계",
  },
  {
    CID: 5247,
    category1: "국내도서",
    category2: "자기계발",
    category3: "인간관계",
  },
  {
    CID: 70226,
    category1: "국내도서",
    category2: "자기계발",
    category3: "협상/설득/화술",
  },
  {
    CID: 70229,
    category1: "국내도서",
    category2: "자기계발",
    category3: "기획/보고",
  },
  {
    CID: 70232,
    category1: "국내도서",
    category2: "자기계발",
    category3: "리더십",
  },
  {
    CID: 70239,
    category1: "국내도서",
    category2: "자기계발",
    category3: "힐링",
  },
  {
    CID: 104384,
    category1: "외국도서",
    category2: "자기계발",
    category3: "감정장애",
  },
  {
    CID: 104387,
    category1: "외국도서",
    category2: "자기계발",
    category3: "강박행동",
  },
  {
    CID: 104392,
    category1: "외국도서",
    category2: "자기계발",
    category3: "약물남용/중독",
  },
  {
    CID: 104396,
    category1: "외국도서",
    category2: "자기계발",
    category3: "자기관리",
  },
  {
    CID: 104401,
    category1: "외국도서",
    category2: "자기계발",
    category3: "자아성장",
  },
  {
    CID: 104406,
    category1: "외국도서",
    category2: "자연과학",
    category3: "과학",
  },
  {
    CID: 104443,
    category1: "외국도서",
    category2: "자연과학",
    category3: "수학",
  },
  {
    CID: 104446,
    category1: "외국도서",
    category2: "자연과학",
    category3: "수학",
  },
  {
    CID: 104482,
    category1: "외국도서",
    category2: "자연과학",
    category3: "자연생태",
  },
  {
    CID: 104969,
    category1: "외국도서",
    category2: "컴퓨터",
    category3: "데스크탑 애플리케이션",
  },
  {
    CID: 104978,
    category1: "외국도서",
    category2: "컴퓨터",
    category3: "데이터 전송 시스템",
  },
  {
    CID: 104985,
    category1: "외국도서",
    category2: "컴퓨터",
    category3: "디지털 미디어",
  },
  {
    CID: 105009,
    category1: "외국도서",
    category2: "컴퓨터",
    category3: "운영체제(OS)",
  },
  {
    CID: 105018,
    category1: "외국도서",
    category2: "컴퓨터",
    category3: "웹",
  },
  {
    CID: 105035,
    category1: "외국도서",
    category2: "컴퓨터",
    category3: "프로그래밍",
  },
  {
    CID: 1714,
    category1: "국내도서",
    category2: "컴퓨터/모바일",
    category3: "프로그래밍 개발/방법론",
  },
  {
    CID: 2632,
    category1: "국내도서",
    category2: "컴퓨터/모바일",
    category3: "그래픽/멀티미디어",
  },
  {
    CID: 2663,
    category1: "국내도서",
    category2: "컴퓨터/모바일",
    category3: "웹디자인/홈페이지",
  },
  {
    CID: 2737,
    category1: "국내도서",
    category2: "컴퓨터/모바일",
    category3: "컴퓨터 공학",
  },
  {
    CID: 2756,
    category1: "국내도서",
    category2: "컴퓨터/모바일",
    category3: "프로그래밍 개발/방법론",
  },
  {
    CID: 6346,
    category1: "국내도서",
    category2: "컴퓨터/모바일",
    category3: "PC/게임/디지털 카메라",
  },
  {
    CID: 6589,
    category1: "국내도서",
    category2: "컴퓨터/모바일",
    category3: "프로그래밍 개발/방법론",
  },
];
