type book = {
  id: number;
  PAGE_NO?: string;
  TOTAL_COUNT?: string;
  TITLE?: string;
  VOL?: string;
  SERIES_TITLE?: string;
  SERIES_NO?: string;
  AUTHOR?: string;
  EA_ISBN?: string;
  EA_ADD_CODE?: string;
  SET_ISBN?: string;
  SET_ADD_CODE?: string;
  SET_EXPRESSION?: string;
  PUBLISHER?: string;
  EDITION_STMT?: string;
  PRE_PRICE?: string;
  KDC?: string;
  DDC?: string;
  PAGE?: string;
  BOOK_SIZE?: string;
  FORM?: string;
  PUBLISH_PREDATE?: string;
  SUBJECT?: string;
  EBOOK_YN?: string;
  CIP_YN?: string;
  CONTROL_NO?: string;
  TITLE_URL?: string;
  BOOK_TB_CNT_URL?: string;
  BOOK_INTRODUCTION_URL?: string;
  BOOK_SUMMARY_URL?: string;
  PUBLISHER_URL?: string;
  INPUT_DATE?: string;
  UPDATE_DATE?: string;
};
export type bookType = book[];
